const LOAD_USERS_START = "LOAD_USERS_START";
const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
const LOAD_USERS_ERROR = "LOAD_USERS_ERROR";

const CREATE_USER_START = "CREATE_USER_START";
const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
const CREATE_USER_ERROR = "CREATE_USER_ERROR";

const DELETE_USER_START = "DELETE_USER_START";
const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export { LOAD_USERS_START, LOAD_USERS_SUCCESS, LOAD_USERS_ERROR };
export { CREATE_USER_START, CREATE_USER_SUCCESS, CREATE_USER_ERROR };
export { DELETE_USER_START, DELETE_USER_SUCCESS, DELETE_USER_ERROR };
